name: dotnet-release

on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: "Pre-release"
    runs-on: ".net 7"
    steps:
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.cs

